name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker build
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: userunknownn 
        password: ${{ secrets.PASSWORD_DOCKER_HUB }} 
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: programa
        
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
       context: .
       file: ./Dockerfile
       push: true
       tags: userunknownn/go_ci:${{ github.ref_name }}
